# Generated by Django 6.0.1 on 2026-01-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=280, verbose_name='Ta radinerie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('votes_genie', models.PositiveIntegerField(default=0)),
                ('votes_rat', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
